__author__ = 'mohammad'

class TokenType:
    (REPEAT_TOK, PERIOD_TOK, SEMICOLON_TOK, MODULE_TOK, RIGHT_PAREN_, LEFT_PAREN_,
     BEGIN_TOK, END_TOK, IF_TOK, WriteInt_TOK, UNTIL_TOK,
     ID_TOK, WHILE_TOK, ELSE_TOK,  THEN_TOK, ASSIGN_OP, LIT_INT,
     ADD_TOK, SUB_TOK, MUL_TOK, DIV_TOK, EQ_TOK, NE_TOK, LT_TOK,
     LE_TOK, GT_TOK, GE_TOK, EOS_TOK, DO_TOK)= range (0, 29)
